# -*- coding: utf-8 -*-
"""TAREARDED

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11SxzDL15l--U299CnBL5j2U7uboglEK0
"""

import pandas as pd
datos=pd.read_csv('presenciaredes.csv',header=0)
datos#Mostramos la tabla 
ene=datos.iloc[7:8,3:4] #Ubicamos los valores a trabajar
ene
jun=datos.iloc[7:8,8:9]#Ubicamos los valores a trabajar
jun
enero=62404 #Guardamos ambos valores
juni=67496
diferencia=juni-enero #Realizamos los calculos de la diferencia 
print("La diferencia entre los meses de enero y junio en followers en twitter es: ")
diferencia #Mostramos que diferencia existe