# -*- coding: utf-8 -*-
"""Tarea 1 ED

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11SxzDL15l--U299CnBL5j2U7uboglEK0
"""

import pandas as pd
datos=pd.read_csv('presenciaredes.csv',header=0)
datos
ene=datos.iloc[7:8,3:4]
ene
jun=datos.iloc[7:8,8:9]
jun
enero=62404
juni=67496
diferencia=juni-enero
print("La diferencia entre los meses de enero y junio en followers en twitter es: ")
diferencia